### ISSUE TITLE
YEAR issue

### ISSUE THREAD

**Issue by alod83** [europeana/search#17]
Dear all,
I'm not sure if this is the correct place to put this issue.
When doing a search on the Europeana search bar, the keyword YEAR does not work in some cases, i.e. for example if I type: YEAR:[1525 TO 1527] it works correctly, but if the first year is less than 1000 the search does not work (e.g. YEAR:[300 TO 1945] does not provide any result). In addition, years before Christ are not supported.

**Comment by marrerom** [comment]
Dear Angelica,
the issue is that YEAR is not indexed as a date, only as a string of characters, so when we search by ranges there, the first one has to precede alphabetically the second one. That is why YEAR:[1525 TO 1527] is working ('5' goes before '7' as a character) but YEAR:[300 TO 1945] is not ('3' goes after '1' alphabetically). We will fix this problem in the next update.
If you find any other problem related to search, please send them to api@europena.eu
Thank you!
